/**
 * WASM Loader for RazorConsole Gallery
 * 
 * This module handles loading and initializing the RazorConsole.Gallery WASM module,
 * and provides an interface for bidirectional communication between the browser and
 * the .NET WASM runtime.
 */

export interface WasmModule {
  sendInput: (input: string) => void;
  sendKeyPress: (key: string) => void;
  dispose: () => void;
}

export interface WasmCallbacks {
  onOutput?: (data: string) => void;
  onError?: (error: string) => void;
  onReady?: () => void;
}

/**
 * Loads the RazorConsole.Gallery WASM module
 * @param callbacks Callbacks for handling WASM events
 * @returns Promise that resolves to a WasmModule interface
 */
export async function loadWasmModule(callbacks: WasmCallbacks): Promise<WasmModule> {
  const { onOutput, onError, onReady } = callbacks;

  try {
    // Load the main.ts module from WASM bundle
    const wasmBaseUrl = new URL('./', getWasmBundleUrl());
    const mainModuleUrl = new URL('./main.ts', wasmBaseUrl).href;
    
    // Dynamically import the WASM module
    const { initRazorConsole, onConsoleOutput } = await import(/* @vite-ignore */ mainModuleUrl);
    
    // Set up console output capture
    if (onOutput) {
      onConsoleOutput(onOutput);
    }
    
    // Initialize WASM and start the application
    const wasmModule = await initRazorConsole();
    
    // Notify ready
    if (onReady) {
      onReady();
    }
    
    return {
      sendInput: (input: string) => {
        // Send character input
        wasmModule.sendKey(input, false, false, false);
      },
      sendKeyPress: (key: string) => {
        // For special keys, pass them directly
        wasmModule.sendKey(key, false, false, false);
      },
      dispose: () => {
        console.log("Disposing WASM module");
      },
    };
  } catch (error) {
    if (onError) {
      onError(error instanceof Error ? error.message : "Unknown error loading WASM");
    }
    throw error;
  }
}

/**
 * Gets the URL for the WASM bundle
 * This should point to the AppBundle generated by the .NET build
 */
export function getWasmBundleUrl(): string {
  // Use environment variable or default to production path
  const basePath = import.meta.env.BASE_URL || '/';
  return `${basePath}wasm/_framework/dotnet.js`;
}

/**
 * Checks if WASM is supported in the current browser
 */
export function isWasmSupported(): boolean {
  try {
    if (typeof WebAssembly === "object" &&
        typeof WebAssembly.instantiate === "function") {
      const module = new WebAssembly.Module(Uint8Array.of(0x0, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00));
      if (module instanceof WebAssembly.Module) {
        return new WebAssembly.Instance(module) instanceof WebAssembly.Instance;
      }
    }
  } catch (e) {
    // WebAssembly not supported
  }
  return false;
}
