name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore RazorConsole.sln

      - name: Build
        run: dotnet build RazorConsole.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test RazorConsole.sln --configuration Release --no-build --verbosity normal
