name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - '*.*.*'
  workflow_dispatch:

jobs:
  package:
    name: Build, test, and pack
    runs-on: ubuntu-latest
    outputs:
      package-path: ${{ steps.pack.outputs.package-path }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore RazorConsole.sln

      - name: Build
        run: dotnet build RazorConsole.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test RazorConsole.sln --configuration Release --no-build --verbosity normal

      - name: Pack libraries
        id: pack
        run: |
          dotnet pack RazorConsole.sln \
            --configuration Release \
            --no-build \
            --output artifacts/packages
          echo "package-path=artifacts/packages" >> "$GITHUB_OUTPUT"

      - name: Upload NuGet packages
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: |
            artifacts/packages/*.nupkg
            artifacts/packages/*.snupkg
          if-no-files-found: warn
          retention-days: 90

      - name: Push packages to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          for package in artifacts/packages/*.nupkg; do
            dotnet nuget push "$package" \
              --api-key "$NUGET_API_KEY" \
              --source https://api.nuget.org/v3/index.json \
              --skip-duplicate
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/packages/*.nupkg
            artifacts/packages/*.snupkg
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}